=== Stiwyy/xml-dataformat/src/main/resources/files/adressen02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="adressliste">
		<xsd:complexType>
			<xsd:sequence>
			
				<xsd:element name="adresse" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
						
							<xsd:element name="name" type="xsd:string"/>
							<xsd:element name="vorname" type="xsd:string"/>
							<xsd:element name="strasse" type="xsd:string"/>
							<xsd:element name="hausnummer" type="xsd:int"/>
							<xsd:element name="telefonnummer" type="xsd:string" minOccurs="0"/>
							
							<xsd:element name="kinder" minOccurs="0" maxOccurs="1">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="kind" minOccurs="1" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="vorname" type="xsd:string"/>
													<xsd:element name="geburtsjahr" type="xsd:gYear"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										
									</xsd:sequence>
								</xsd:complexType>
								
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
					
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		
	</xsd:element>
</xsd:schema>

=== Stiwyy/xml-dataformat/src/main/resources/files/adressen02.xml
<?xml version="1.0" encoding="UTF-8" ?> 
<adressliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\adressen02.xsd">
	<adresse>
		<name>muster</name> 
		<vorname>hans</vorname> 
		<strasse>mustergasse</strasse> 
		<hausnummer>20</hausnummer> 
		<telefonnummer>+4143222222222</telefonnummer> 
		<kinder>
			<kind>
				<vorname>Peter</vorname>
				<geburtsjahr>1995</geburtsjahr>
			</kind>
			<kind>
				<vorname>egon</vorname>
				<geburtsjahr>1890</geburtsjahr>
			</kind>
		</kinder>
	</adresse>
	<adresse>
		<name>studer</name> 
		<vorname>eva</vorname> 
		<strasse>stadtgasse</strasse> 
		<hausnummer>15</hausnummer> 	
	</adresse>
</adressliste>
